config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    get 'customers/mypage', :to => "customers#show", as: "customers"
    get 'customers/mypage/edit', :to => "customers#edit", as: "edit_customers"
    patch 'customers/mypage', :to => "customers#update"
    get 'customers/mypage/confirm', :to => "customers#confirm"
    patch 'customers/mypage/unsubscribe', :to => "customers#unsubscribe"
    resources :addresses, only: [:index, :edit, :destroy, :update, :create]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all', :to => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "orders/completion"=> "orders#completion"
    resources :orders, only: [:index, :show, :index, :create, :new]
    post "orders/confirm" => "orders#confirm"


  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/', :to => "homes#top"
    resources :genres, only: [:create, :edit, :index, :update]
    resources :items, only: [:create, :edit, :index, :update, :new, :show]
    resources :customers, only: [:edit, :index, :update, :show]
    resources :orders, only: [:show, :update]
    patch 'ordered_products/:id', :to => "ordered_products#update", as: "update_ordereb"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image
    belongs_to :customer
    belongs_to :item
    def subtotal
    item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :cart_items
  def fullname
    first_name+last_name
  end
  def fullname_kana
    first_name_kana+last_name_kana
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :ordered_products
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_products
  enum payment: { credit_card: 0, transfer: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "製作不可": 0, "製作待ち": 1,"製作中": 2,"製作完了": 3 }
  def with_tax_price
    (price * 1.1).floor
  end
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])

  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path
  end

   private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
    private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @status = ["製作不可", "製作待ち", "製作中", "製作完了"]
    @order_status = ["入金待ち", "入金確認", "製作中", "発送準備中", "発送済み"]
  end
  def update
   order = Order.find(params[:id])
   order.update(orders_params)
   if order.status == "入金確認"
     order.ordered_products.update(making_status:1)
   end
   redirect_to admin_order_path(order.id)
  end

   private

  def orders_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin
        admin_path
      when Customer
        root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mx-auto" style="width: 1000px;">
  <p id="notice"></p>
  <h4>会員情報編集</h4>
   <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>

       <div class="form-group row m-2">
          <label class="col-sm-2 col-form-label">氏名</label>
           <div class="col-sm-3">
             <%= f.text_field :first_name %>
           </div>
           <div class="col-sm-5">
             <%= f.text_field :last_name %>
           </div>
           <div class="col-sm-2">
           </div>

            <label class="col-sm-2 col-form-label">フリガナ</label>
            <div class="col-sm-3">
              <%= f.text_field :first_name_kana %>
            </div>
            <div class="col-sm-5">
              <%= f.text_field :last_name_kana %>
            </div>
            <div class="col-sm-2">
            </div>

            <label class="col-sm-2 col-form-label">郵便番号</label>
            <div class="col-sm-10">
            <%= f.text_field :postal_code %>
            </div>

            <label class="col-sm-2 col-form-label">住所</label>
            <div class="col-sm-10">
            <%= f.text_field :address %>
            </div>

            <label class="col-sm-2 col-form-label">電話番号</label>
            <div class="col-sm-10">
            <%= f.text_field :telephone_number %>
            </div>

            <label class="col-sm-2 col-form-label">メールアドレス</label>
            <div class="col-sm-10">
            <%= f.email_field :email %>
            </div>


            <label class="col-sm-2 col-form-label">会員ステータス</label>
            <div class="col-sm-10">
             <%= f.radio_button :is_active, 1, checked: true %>有効
   　         <%= f.radio_button :is_active, 0 %>退会<br>
            </div>

     <%= f.submit "変更を保存", class:"btn btn-success" %>
   <% end %>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h1>会員一覧</h1>
  <table class="table tanle-hover table-inverse">
   <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>

      </tr>
    </thead>
   <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td>
         <%= customer.id %>
    　    </td>
         <td><%= link_to admin_customer_path(customer.id) do %>
           <%= customer.fullname %>
           <% end %></td>
         <td><%= customer.email %></td>
          <td>
         <% if customer.is_active %>
           有効
         <% else %>
           退会
         <% end %>
      </td>
    </tr>
  <% end %>
    </tbody>
   </table>
    <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/customers/show.html.erb
 <div class="container mx-auto" style="width: 600px;">
   <p id="notice"></p>
    <h4><%= @customer.fullname %>の会員詳細</h4>


      <div class="customer-group row m-5">

         <label class="col-sm-5 col-item-label">会員ID</label>
           <div class="col-sm-7">
              <%= @customer.id %>
           </div>

            <label class="col-sm-5 col-form-label">氏名</label>
            <div class="col-sm-7">
              <%= @customer.fullname %>
            </div>

            <label class="col-sm-5 col-form-label">カナ</label>
            <div class="col-sm-7">
              <%= @customer.fullname_kana %>
            </div>

            <label class="col-sm-5 col-form-label">郵便番号</label>
            <div class="col-sm-7">
              <%= @customer.postal_code %>
            </div>

            <label class="col-sm-5 col-form-label">住所</label>
            <div class="col-sm-7">
              <%= @customer.address %>
            </div>

            <label class="col-sm-5 col-form-label">電話番号</label>
            <div class="col-sm-7">
              <%= @customer.telephone_number %>
            </div>

            <label class="col-sm-5 col-form-label">メールアドレス</label>
            <div class="col-sm-7">
              <%= @customer.email %>
            </div>

            <label class="col-sm-5 col-form-label mt-3">会員ステータス</label>
            <div class="col-sm-7">
              <% if @customer.is_active %>
              　<p class="text-success">有効</p>
            　<% else %>
              　退会
            　<% end %>
            </div>
          </div>

    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "col-xs-12 btn btn-primary" %>
  </div>