config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    get 'customers/mypage', :to => "customers#show", as: "customers"
    get 'customers/mypage/edit', :to => "customers#edit", as: "edit_customers"
    patch 'customers/mypage', :to => "customers#update"
    get 'customers/mypage/confirm', :to => "customers#confirm"
    patch 'customers/mypage/unsubscribe', :to => "customers#unsubscribe"
    resources :addresses, only: [:index, :edit, :destroy, :update, :create]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all', :to => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "orders/completion"=> "orders#completion"
    resources :orders, only: [:index, :show, :index, :create, :new]
    post "orders/confirm" => "orders#confirm"


  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/', :to => "homes#top"
    resources :genres, only: [:create, :edit, :index, :update]
    resources :items, only: [:create, :edit, :index, :update, :new, :show]
    resources :customers, only: [:edit, :index, :update, :show]
    resources :orders, only: [:show, :update]
    patch 'ordered_products/:id', :to => "ordered_products#update", as: "update_ordereb"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image
    belongs_to :customer
    belongs_to :item
    def subtotal
    item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :cart_items
  def fullname
    first_name+last_name
  end
  def fullname_kana
    first_name_kana+last_name_kana
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :ordered_products
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_products
  enum payment: { credit_card: 0, transfer: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "製作不可": 0, "製作待ち": 1,"製作中": 2,"製作完了": 3 }
  def with_tax_price
    (price * 1.1).floor
  end
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
    private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @status = ["製作不可", "製作待ち", "製作中", "製作完了"]
    @order_status = ["入金待ち", "入金確認", "製作中", "発送準備中", "発送済み"]
  end
  def update
   order = Order.find(params[:id])
   order.update(orders_params)
   if order.status == "入金確認"
     order.ordered_products.update(making_status:1)
   end
   redirect_to admin_order_path(order.id)
  end

   private

  def orders_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin
        admin_path
      when Customer
        root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
 <div class="container">
    <h4>ジャンル編集</h4>
    <div class="m-5">
      <%= form_with model: @genre ,url: admin_genre_path(@genre) do |f| %>
      <label class="mr-5">ジャンル名</label>
      <%= f.text_field :name %>


      <%= f.submit "変更を保存",class:"btn btn-success" %>
    <% end %>
    </div>
  </div>

app/views/admin/genres/index.html.erb
 <div class="container">

    <h4>ジャンル一覧・追加</h4>
    <div class="m-5">
      <%= form_with model: @genre ,url: admin_genres_path do |f| %>
      <label class="mr-5">ジャンル名</label>
      <%= f.text_field :name %>

      <%= f.submit "新規登録",class:"btn btn-success" %>
      <% end %>

    </div>
    <div>
      <table class="table tanle-hover table-inverse">
        <thead>
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
     <tbody>
    <% @genres.each do |genre| %>
           <tr>
           <td><%= genre.name %></td>
           <td><%= link_to "編集する", edit_admin_genre_path(genre),class:"btn btn-success btn-sm" %></td>
           </tr>
    <% end %>
      </tbody>
     </table>
 </div>

app/views/admin/homes/top.html.erb
<div class="container">
<h2>注文履歴一覧</h2>
<table class="table tanle-hover table-inverse">
 <thead>
    <tr>
      <th>購入日付</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>
 <tbody>
<% @orders.each do |order| %>
<tr>
  <td><%= link_to admin_order_path(order.id) do %>
    <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
    <% end %>
    </td>
  <td><%= order.customer.fullname %></td>
  <td><%= order.ordered_products.sum(:amount)%></td>
  <td></td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/admin/items/edit.html.erb
<main>
  <body>
    <div class="container mx-auto" style="width: 600px;">
      <h4>商品編集</h4>
      <div class="row">
         <p id="notice"></p>

         <%= form_with model: @item, url: admin_item_path(@item) do |f| %>

            <div class="form-group row">
          <label class="col-sm-5 col-form-label">商品画像</label>
           <div class="col-sm-7">
             <%= f.file_field :image, placeholder: "Image", accept: "image/*" %>
           </div>

            <label class="col-sm-5 col-form-label">商品名</label>
            <div class="col-sm-7">
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
            </div>

            <label class="col-sm-5 col-form-label">商品説明</label>
            <div class="col-sm-7">
            <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction"%>
            </div>

            <label class="col-sm-5 col-form-label">ジャンル</label>
            <div class="col-sm-7">
            <%= f.collection_select :genre_id, Genre.all, :id, :name %>
            </div>

            <label class="col-sm-5 col-form-label">税抜き価格</label>
            <div class="col-sm-7">
            <%= f.number_field :price %>円
            </div>

            <label class="col-sm-5 col-form-label">販売ステータス</label>
            <div class="col-sm-7">
             <%= f.radio_button :is_active, 1, checked: true %>販売中
        　    <%= f.radio_button :is_active, 0 %>販売停止中<br>
            </div>
           </div>
            <%= f.submit "変更を保存", class:"btn btn-success" %>

          <% end %>
      </div>
    </div>
  </div>
 </body>
</main>

app/views/admin/items/index.html.erb
<div class="container">
<h2>商品一覧</h2>
<div class="d-flex justify-content-end m-3">
<%= link_to new_admin_item_path do %>
  <i class="fas fa-plus-circle fa-2x"></i>
  <% end %>
</div>
<table class="table tanle-hover table-inverse">
 <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜き価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
 <tbody>
<% @items.each do |item| %>
<tr>
  <td><%= item.id %></td>
  <td><%= link_to admin_item_path(item.id) do %>
    <%= item.name %>
    <% end %>
    </td>
  <td><%= item.price %></td>
  <td><%= item.genre.name %></td>
  <td>
    <% if item.is_active %>
      販売中
    <% else %>
      販売停止中
    <% end %>
  </td>
</tr>
<% end %>
</tbody>
</table>

<%= paginate @items, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/items/new.html.erb
<main>
  <body>
    <div class="container mx-auto" style="width: 600px;">
      <h4>商品新規登録</h4>
       <div class="row">
         <p id="notice"></p>

      <%= form_with model: @item, url: admin_items_path do |f| %>
          <div class="form-group row">
          <label class="col-sm-5 col-form-label">商品画像</label>
           <div class="col-sm-7">
            <%= f.file_field :image, accept: "image/*" %>
           </div>

            <label class="col-sm-5 col-form-label">商品名</label>
            <div class="col-sm-7">
            <%= f.text_field :name %>
            </div>

            <label class="col-sm-5 col-form-label">商品説明</label>
            <div class="col-sm-7">
            <%= f.text_area :introduction %>
            </div>

            <label class="col-sm-5 col-form-label">ジャンル</label>
            <div class="col-sm-7">
            <%= f.collection_select :genre_id, Genre.all, :id, :name %>
            </div>

            <label class="col-sm-5 col-form-label">税抜き価格</label>
            <div class="col-sm-7">
            <%= f.number_field :price %>円
            </div>

            <label class="col-sm-5 col-form-label">販売ステータス</label>
            <div class="col-sm-7">
            <%= f.radio_button :is_active, 1, checked: true %>販売中
          　<%= f.radio_button :is_active, 0 %>販売停止中<br>
            </div>
           </div>
            <%= f.submit "新規登録",class:"btn btn-success" %><br>

          <% end %>

           <%= yield %>
      </div>
    </div>
</body>
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-3">
        <h4>商品詳細</h4>
            <%= image_tag @item.image, size: "200x200" %>
        </div>
          <div class="col-9">
            <div class="item-group row">

              <label class="col-sm-5 col-item-label">商品名</label>
           <div class="col-sm-7">
              <%= @item.name %>
           </div>

            <label class="col-sm-5 col-form-label">商品説明</label>
            <div class="col-sm-7">
              <%= @item.introduction %>
            </div>

            <label class="col-sm-5 col-form-label">ジャンル</label>
            <div class="col-sm-7">
              <%= @item.genre.name %>
            </div>

            <label class="col-sm-5 col-form-label">税込み価格(税抜き価格)</label>
            <div class="col-sm-7">
              <%= @item.with_tax_price %>（<%= @item.price %>）円
            </div>

            <label class="col-sm-5 col-form-label">販売ステータス</label>
            <div class="col-sm-7">
              <% if @item.is_active %>
                販売中
             <% else %>
                販売停止中
             <% end %>
            </div>

          <%= link_to "編集する", edit_admin_item_path(@item),class:"btn btn-success btn-sm mt-5" %>
      </div>
    </div>
  </div>
</main>

app/views/admin/orders/show.html.erb
<div class="container">
  <h2>注文履歴一覧</h2>
    <table class="table tanle-hover table-inverse ">
       <title>注文情報</title>
        <tr>
          <th>購入者</th>
            <td><%= link_to admin_customer_path(@order.customer.id) do %>
            <%= @order.customer.fullname %>
          　<% end %></td>
        </tr>
        <tr>
          <th>注文日</th>
            <td><%=@order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
            <td>
              <%= @order.postal_code + @order.address %><br>
              <%= @order.customer.fullname %>
      　　    </td>
      　</tr>
      　<tr>
          <th>支払方法</th>
          　<td><%= @order.payment_i18n %></td>
        </tr>
        <tr>
          <th>ステータス</th>
           <%= form_with model: @order, url: admin_order_path(@order.id) do |s| %>
            <td>
              <%= s.select :status, @order_status %>
              <%= s.submit "更新", class:"btn btn-success btn-sm" %>
            </td>
           <% end %>
        </tr>
      </thead>
    </table>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-8">
        <table class="table tanle-hover table-inverse">
          <h6>注文内容</h6>
         <thead>
            <tr>
              <th>商品名</th>
              <th>単価(税込)</th>
              <th>数量</th>
              <th>小計</th>
              <th>製作ステータス</th>
            </tr>
          </thead>
         <tbody>
        <% @order.ordered_products.each do |f| %>
        <tr>
          <td><%= f.item.name %></td>
          <td><%= f.with_tax_price %></td>
          <td><%= f.amount %></td>
          <td>
            <%= f.subtotal %>
          </td>
             <%= form_with model: f, url: admin_update_ordereb_path(f.id) do |s| %>
          <td>
            <%= s.select :making_status, @status %>
            <%= s.submit "更新", class:"btn btn-success btn-sm" %>
          </td>
            <% end %>
          <% end %>
        </tbody>
        </table>
      </div>
      <div class="col-4">
      <table>
 <thead>
  <tr>
    <th>商品合計</th>
      <td><%= @order.total_payment - 800 %>円</td>
    </tr>
    <tr>
      <th>配送料</th>
        <td>800円  </td>
  　</tr>
  　<tr>
      <th>ご請求額</th>
      　<td><%= @order.total_payment %>円</td>
    </tr>

    </thead>
   </table>
  </div>
 </div>
</div>