config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about", as: "about"
    get 'customers/mypage', :to => "customers#show", as: "customers"
    get 'customers/mypage/edit', :to => "customers#edit", as: "edit_customers"
    patch 'customers/mypage', :to => "customers#update"
    get 'customers/mypage/confirm', :to => "customers#confirm"
    patch 'customers/mypage/unsubscribe', :to => "customers#unsubscribe"
    resources :addresses, only: [:index, :edit, :destroy, :update, :create]
    resources :items, only: [:index, :show]
    delete '/cart_items/destroy_all', :to => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get "orders/completion"=> "orders#completion"
    resources :orders, only: [:index, :show, :index, :create, :new]
    post "orders/confirm" => "orders#confirm"


  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {

  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/', :to => "homes#top"
    resources :genres, only: [:create, :edit, :index, :update]
    resources :items, only: [:create, :edit, :index, :update, :new, :show]
    resources :customers, only: [:edit, :index, :update, :show]
    resources :orders, only: [:show, :update]
    patch 'ordered_products/:id', :to => "ordered_products#update", as: "update_ordereb"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    has_one_attached :image
    belongs_to :customer
    belongs_to :item
    def subtotal
    item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :addresses, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :cart_items
  def fullname
    first_name+last_name
  end
  def fullname_kana
    first_name_kana+last_name_kana
  end


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :ordered_products
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordered_products
  enum payment: { credit_card: 0, transfer: 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { "製作不可": 0, "製作待ち": 1,"製作中": 2,"製作完了": 3 }
  def with_tax_price
    (price * 1.1).floor
  end
  def subtotal
    item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
    private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
   item = Item.find(params[:id])
   item.update(item_params)
   redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
      when Admin
        admin_path
      when Customer
        root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LOGO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="d-flex flex-column vh-100">
    <header>

      <nav class="navbar navbar-expand-lg" style='border-bottom: 1px solid'>
        <div class="container">
         <a class="navbar-brand" href="/">
           <span>LOGO</span>
         </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if current_customer %>
            <li class="nav-item">
              <%= link_to "マイページ",customers_path, class: 'btn btn-outline-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧",items_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "カート",cart_items_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",destroy_customer_session_path, method: :delete, class: 'btn btn-outline-dark' %>

            </li>
            <% elsif current_admin %>
             <li class="nav-item">
              <%= link_to "商品一覧",admin_items_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "会員一覧",admin_customers_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "注文履歴一覧",admin_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧",admin_genres_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %>

            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "About",about_path, class: 'btn btn-outline-dark'  %>


            </li>
            <li class="nav-item">
              <%= link_to "商品一覧",items_path, class: 'btn btn-outline-dark' %>


            </li>
            <li class="nav-item">
              <%= link_to "新規登録",new_customer_registration_path, class: 'btn btn-outline-dark' %>

            </li>
            <li class="nav-item">
              <%= link_to "ログイン",new_customer_session_path, class: 'btn btn-outline-dark' %>
            </li>
            <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>
      <p><%= flash[:notice] %></p>
    <main>
      <p id="notice"></p>
    <%= yield %>
    </main>
      <p id="notice"></p>
    <footer class=" bg-dark pt-5 pb-4 mt-5">
    </footer>
  </body>
</html>